Language="VBSCRIPT"

Sub CATMain()

dim plme as PLMEntities
set plme =CATIA.ActiveEditor.ActiveObject

dim plmeos as VPMOccurrences
set plmeos = plme.Occurrences



'''''''''''''''''''''''''''''katsoo onko valinta osa,alikokoonpano,pääkokoonpano

On Error Resume Next
dim plment as PLMEntities
set plment =CATIA.ActiveEditor.Selection


'''''''''''''''''''odottaa käyttäjältä inputtia''''''''''''''''''''''''''''''''''''''''''
Dim oInputObjectType(3)
    oInputObjectType(3) = "AnyObject"
    oInputObjectType(2) = "VPMRootOccurrence"
    oInputObjectType(1) = "VPMOccurrence"
    oInputObjectType(0) = "VPMRepInstance"

Dim strStatus As String
strStatus = plment.SelectElement(oInputObjectType, "Select a Element from spec tree", True)

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

dim sel
set sel = plment.Item(1)

If Err.Number <>0 Then
	MsgBox("Poimi osa tai kokoonpano")
	Wscript.Quit
	
End if

'msgbox(sel.type)

On Error Goto 0



Dim oVPMOccOnSelectedObject As PLMOccurrence
Set oVPMOccOnSelectedObject = sel.Value

'polku 1 jos kyseessä komponentti tai kokoonpanon ylin taso
On Error Resume Next
Set oVPMEntityOnSelectedObject = oVPMOccOnSelectedObject.PLMEntity
On Error Goto 0

'polku 2 jos kyseessä alikokoonpano
On Error Resume Next
Dim oVPMInst As VPMInstance
Set oVPMInst = oVPMOccOnSelectedObject.InstanceOccurrenceOf     
Dim oVMPRef As VPMReference
Set oVPMRef = oVPMInst.ReferenceInstanceOf
Set oVPMEntityOnSelectedObject = oVPMRef
On Error Goto 0

'''''''''''''''''''''''''''''

'oVPMEntityOnSelectedObject.SetAttributeValue("V_Thickness"), "2"
'oVPMEntityOnSelectedObject.SetAttributeValue("V_fromExternalID"), ""

msgbox("Picked part data from:"+oVPMEntityOnSelectedObject.GetAttributeValue("PLM_ExternalID"))

dim temp_desc as string
dim temp_title as string
dim temp_bu as string
dim temp_finishing as string
dim temp_material_spec as string
dim temp_desc2 as string
dim temp_uom as string
dim temp_comp_cat as string

dim temp_id as string
dim temp_id_start as string

temp_desc = oVPMEntityOnSelectedObject.GetAttributeValue("V_description")
temp_title = oVPMEntityOnSelectedObject.GetAttributeValue("V_Name")
temp_bu = oVPMEntityOnSelectedObject.GetAttributeValue("Business_Unit")
temp_finishing = oVPMEntityOnSelectedObject.GetAttributeValue("Finishing")
temp_material_spec = oVPMEntityOnSelectedObject.GetAttributeValue("Material_spec")
temp_desc2 = oVPMEntityOnSelectedObject.GetAttributeValue("Description2")
temp_uom = oVPMEntityOnSelectedObject.GetAttributeValue("UOM")
temp_comp_cat = oVPMEntityOnSelectedObject.GetAttributeValue("Component_Category")

temp_id = oVPMEntityOnSelectedObject.GetAttributeValue("PLM_ExternalID")

if Left(temp_id,1)="N" then
	'msgbox("found N")
	temp_id_start="N"
end if

if Left(temp_id,1)="S" then
	'msgbox("found S")
	temp_id_start="S"
end if


'msgbox("Select part to copy metadata to"+temp_value_to_copy)

plment.Clear



Dim oCurrentActiveEditor As Editor
Set oCurrentActiveEditor = CATIA.ActiveEditor
Dim oObjSelection
Set oObjSelection = oCurrentActiveEditor.Selection



'''''''''''''''''''odottaa käyttäjältä uutta valintaa''''''''''''''''''''''''''''''''''''''''''

strStatus = oObjSelection.SelectElement(oInputObjectType, "Select a Element from spec tree", True)

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

if oObjSelection.Count = 1 Then

	

	set sel = plment.Item(1)
	Set oVPMOccOnSelectedObject = sel.Value

	'polku 1 jos kyseessä komponentti tai kokoonpanon ylin taso
	On Error Resume Next
	Set oVPMEntityOnSelectedObject = oVPMOccOnSelectedObject.PLMEntity
	On Error Goto 0

	'polku 2 jos kyseessä alikokoonpano
	On Error Resume Next
	
	Set oVPMInst = oVPMOccOnSelectedObject.InstanceOccurrenceOf     
	
	Set oVPMRef = oVPMInst.ReferenceInstanceOf
	Set oVPMEntityOnSelectedObject = oVPMRef
	On Error Goto 0

	'''''''''''''''''''''''''''''
	
	msgbox("new part selected and metadata updated with data from:"+temp_id)

	''''''''''''''''''''''''''''' kirjoittaa uuden ID:n osalle '''''''''''''''''''''''''''''

	dim temp_new_id as string
	dim new_id as string
	
	temp_new_id = oVPMEntityOnSelectedObject.GetAttributeValue("PLM_ExternalID")

	'''hakee osasta pelkän numero osuuden regexillä ja luo koodin uudelleen poimien alkuperäisen N- tai S- alun ja numeron uudesta''''
	dim temp_new_id_numbers as string
	Set oRE = New RegExp
	oRE.Pattern = "[^0-9]*"
	temp_new_id_numbers=oRE.Replace(temp_new_id, "")
	temp_new_id=temp_id_start+temp_new_id_numbers

	'''''''''''''''''''''''''''''

	oVPMEntityOnSelectedObject.SetAttributeValue("V_description"), temp_desc
	oVPMEntityOnSelectedObject.SetAttributeValue("V_Name"), temp_title 
	oVPMEntityOnSelectedObject.SetAttributeValue("Business_Unit"), temp_bu 
	oVPMEntityOnSelectedObject.SetAttributeValue("Finishing"), temp_finishing 
	oVPMEntityOnSelectedObject.SetAttributeValue("Material_spec"), temp_material_spec 
	oVPMEntityOnSelectedObject.SetAttributeValue("Description2"), temp_desc2 
	oVPMEntityOnSelectedObject.SetAttributeValue("UOM"), temp_uom 
	oVPMEntityOnSelectedObject.SetAttributeValue("Component_Category"), temp_comp_cat

	if temp_id_start = "N" then	
		oVPMEntityOnSelectedObject.SetAttributeValue("PLM_ExternalID"), temp_new_id
	elseif temp_id_start = "S" then
		oVPMEntityOnSelectedObject.SetAttributeValue("PLM_ExternalID"), temp_new_id
	else	
		
	end if
	
end if


End Sub
